### ISSUE TITLE
support for ```m.notice``` and ```m.server_notice``` messages.

### ISSUE THREAD

**Issue by gtalha07** [effektio/effektio#423]
![image](https://user-images.githubusercontent.com/68579938/210805434-1f8c3041-ded8-4b07-9994-54ba15f63138.png)
![image](https://user-images.githubusercontent.com/68579938/210805977-32071fa9-e106-429d-8a94-2cbe6728fffd.png)

**Comment by gnunicorn** [comment]
the matrix spec states that these should be considered regular events by a UI, just have a less prominent tone (so just make them a little more muted compared to regular events - use some light gray instead of white as color?!?) and are only for bots meant to decern regular user messages from bot messages (so bots don't run into a loop). should be fairly straight forward to implement.

**Comment by gtalha07** [comment]
> the matrix spec states that these should be considered regular events by a UI, just have a less prominent tone (so just make them a little more muted compared to regular events - use some light gray instead of white as color?!?) and are only for bots meant to decern regular user messages from bot messages (so bots don't run into a loop). should be fairly straight forward to implement.

Yeah it needs to be distinct apart from usual messages, does this need to be replaced on chat list ```LatestMessage()``` event? Or should it only render room messages?
